title: "Ecos del Alma"
description: "Escritos breves sobre memoria, vínculos y regreso a uno mismo."
baseurl: "/ecos-del-alma"
url: "https://faridSprado.github.io"
author: "Farid Prado"
repo_url: "https://github.com/faridSprado/ecos-del-alma"
timezone: "America/Bogota"

future: true
show_excerpts: true
markdown: kramdown
permalink: /:year/:month/:day/:title/
